### ISSUE TITLE
Angular is not Defined

### ISSUE THREAD

**Issue by iaakash** [taylonr/intro-to-protractor#1]
After launching the app, dev console shows up with error
"angular is not defined" in few different JS files

**Comment by taylonr** [comment]
I've been unable to reproduce this on the `master` branch.

The steps I tried:
1. Cloned repo into new folder
2. Ran `npm install`
3. Ran `grunt`
4. Opened Chrome to `localhost:3000`

I saw the mean.js default page and the console was empty of messages/errors

**Comment by devsaik** [comment]
Even I see this issue

**Comment by taylonr** [comment]
devsaik, do you have any steps to reproduce? I tried last time, but following the install instructions I wasn't able to see it fail, so I'm trying to figure out what's different between what I'm doing and what others are doing.

**Comment by devsaik** [comment]
Hi,
when you say master branch are u poin

**Comment by devsaik** [comment]
Hi,
I think issue is  with downloaded code from pluralsight but not from master branch.., sorry about that ..

**Comment by devsaik** [comment]
You can run a diff to identify what makes it work with master but not with downloaded code from pluralsight..

**Comment by taylonr** [comment]
Hmmm, ok thanks. I'll figure out what is going on with the code that comes from Pluralsight and get them and update.

**Comment by taylonr** [comment]
I've sent the update to Pluralsight to have them use the master branch, we're just waiting on them to push it out.

Thanks for your help.
