### ISSUE TITLE
Bower doesn't install

### ISSUE THREAD

**Issue by thoughtassassin** [taylonr/intro-to-protractor#2]
When I try to `bower install`nothing happens. I don't get a bower components folder.

**Comment by taylonr** [comment]
The components should be placed in the public/lib folder. Do you not see that after running bower install?

**Comment by thoughtassassin** [comment]
I actually looked at the documentation here. I saw that grunt automatically installs the bower components. This is a non-issue. I apologize. However, I might have to start a new issue because after running mongod running on port 27017, the console tells me it cannot connect to mongod.
