### ISSUE TITLE
Error on starting MongoDB

### ISSUE THREAD

**Issue by DanielRunningen** [taylonr/intro-to-protractor#9]
I'm attempting to follow instructions form both the README and from the initial video of module 2 and I have a feeling I'm missing something.

I already have the newer npm installed, so I started with `npm install` on a fresh copy of the repo. This seemed to also take care of the `bower install` command, but I ran it again anyway since that was the next step in the video. The video then says to launch MongoDB with `mongo d` which returns the following:

```
MongoDB shell version v3.6.3
connecting to: mongodb://127.0.0.1:27017/d
2019-07-11T17:58:55.684+0000 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused
2019-07-11T17:58:55.684+0000 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:251:13
@(connect):1:6
exception: connect failed
```

Any suggestions?

**Comment by taylonr** [comment]
Check out this stackoverflow question. It seems to describe a similar issue:
https://stackoverflow.com/questions/26211671/failed-to-connect-to-127-0-0-127017-reason-errno111-connection-refused

**Comment by DanielRunningen** [comment]
I did see this, but that `mongodb` doesn't exist in my `/var/lib` path. They also seem to be using `mongod` instead of `mongo d` (there's no distinction in the video, the direction is verbal only). I tried this and I was told to install `mongodb-server-core`, which I did. `mongo d` resulted in the same error, but running `mongod` now tells me it can't find the `/data/db` directory.

I did find [this](https://stackoverflow.com/questions/7948789/mongod-complains-that-there-is-no-data-db-folder) stackoverflow question addressing the issue, however the solution seems to be suggesting that mongo should be run under a separate user.

This feels like a lot of overhead for what was suggested in the course considering MongoDB isn't really the topic here.

**Comment by taylonr** [comment]
> This feels like a lot of overhead for what was suggested in the course considering MongoDB isn't really the topic here.

I agree. Unfortunately, this doesn't seem to be a common issue, or at a very minimum, this is the first time I've heard of it happening.

For running `mongod` and getting `can't find the /data/db` error, did you verify there is a folder at that location?  If not, could you create one and see if that fixes the problem?

Again, sorry you're running in to this issue.

**Comment by DanielRunningen** [comment]
```
sudo mkdir -p /data/db
sudo chown -R myuser:myuser /data/db
```
The commands above allowed `mongod` to work. I also need to have a separate cli open to use `mongo d`. Is this normal? Do I only need to be using `mongod`?

**Comment by taylonr** [comment]
I'm glad you got it working.

It's normal to have a cli for mongod and a cli for the app.

You shouldn't need to run anything else besides mongo and the app

**Comment by DanielRunningen** [comment]
So, to clarify, I don't need `mongo d`? (This should probably be clarified somewhere since both are valid commands.)

Running the app is through `grunt`, right? That doesn't seem to work either. I've done `sudo npm install -g grunt-cli` and was met with
```
grunt-cli: The grunt command line interface (v1.3.2)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project.
```
Grunt's [Getting Started](https://gruntjs.com/getting-started) page says that running `npm install` on a project that's already got grunt packages in the `package.json` should be sufficient. I did double-check with a quick grep and got
```
package.json:  11:          "start": "grunt",
package.json:  12:          "test": "grunt test",
package.json:  38:          "grunt-cli": "~0.1.13",
package.json:  44:          "grunt-env": "~0.4.1",
package.json:  45:          "grunt-contrib-watch": "~0.6.1",
package.json:  46:          "grunt-contrib-jshint": "~0.10.0",
package.json:  47:          "grunt-contrib-csslint": "^0.2.0",
package.json:  48:          "grunt-ngmin": "0.0.3",
package.json:  49:          "grunt-contrib-uglify": "~0.4.0",
package.json:  50:          "grunt-contrib-cssmin": "~0.9.0",
package.json:  51:          "grunt-nodemon": "~0.2.1",
package.json:  52:          "grunt-concurrent": "~0.5.0",
package.json:  53:          "grunt-mocha-test": "~0.10.0",
package.json:  54:          "grunt-karma": "~0.8.2",
package.json:  55:          "load-grunt-tasks": "~0.4.0",
```
The only thing that seems off to me is that there isn't a `"grunt": "~x.y.z"` line, but again, this is a fresh copy of master and I haven't made any direct changes to this file.

However, before this I had downloaded the project and had forced upgrades to fix vulnerabilities in the packages. _That_ copy does launch using `grunt` but immediately crashes the project with or without running `mongod` in a seperate window (same directory).
```
Running "jshint:all" (jshint) task
>> 46 files lint free.

Running "csslint:all" (csslint) task
Linting public/modules/users/css/users.css...ERROR
[L12:C1]
WARNING: Rule doesn't have all its properties in alphabetical order. Assure properties are in alphabetical order (order-alphabetical) Browsers: All
>> 3 files lint free.

Running "concurrent:default" (concurrent) task
    Running "nodemon:dev" (nodemon) task
    Running "watch" task
    Waiting...
    [nodemon] 1.19.1
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: app/views/**/*.* gruntfile.js server.js config/**/*.js app/**/*.js
    [nodemon] starting `node --debug server.js`
    (node:1111) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.
    [nodemon] app crashed - waiting for file changes before starting...
```

¯\\\_(ツ)\_/¯

**Comment by taylonr** [comment]
Can you move this discussion to the course's discussion tab?

That way if others run in to similar issues they can see ways to solve
theproblem.

**Comment by DanielRunningen** [comment]
Honestly, pluralsight's idea of a discussion forum is pretty bad and not really useful for these types of issues. However, I'm abandoning this attempt since I've been running into issues even without using the provided code.

You can close this if you want. Pretty sure it's a dead end.
